ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
/
connect sys/sys123 as sysdba;
/
--SELECT * FROM ALL_USERS;
GRANT EXECUTE ON DBMS_RLS TO NHOM11;
/
connect NHOM11/123;
/
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
/
--tao role 
CREATE ROLE RL_NHANVIEN;
/
CREATE ROLE RL_QLTRUCTIEP;
/
CREATE ROLE RL_TRUONGPHONG;
/
CREATE ROLE RL_TAICHINH;
/
CREATE ROLE RL_NHANSU;
/
CREATE ROLE RL_TRUONGDA;
/
-- tao view, vpd ung voi tung CS cua cac role
-- CS1:
CREATE OR REPLACE VIEW UV_NHANVIEN_NHANVIEN AS
    SELECT *
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE VIEW UV_NHANVIEN_PHANCONG AS
    SELECT *
    FROM PHANCONG
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
--CS2:
CREATE OR REPLACE VIEW UV_QLTRUCTIEP_NHANVIEN
AS 
SELECT * FROM NHANVIEN WHERE SYS_CONTEXT('USERENV','SESSION_USER') = MANQL OR SYS_CONTEXT('USERENV','SESSION_USER') = MANV; 
/
CREATE OR REPLACE VIEW UV_QLTRUCTIEP_PHANCONG
AS 
SELECT PHANCONG.* FROM PHANCONG JOIN NHANVIEN ON PHANCONG.MANV = NHANVIEN.MANV WHERE SYS_CONTEXT('USERENV','SESSION_USER') = NHANVIEN.MANQL OR SYS_CONTEXT('USERENV','SESSION_USER') = NHANVIEN.MANV; 
/
CREATE OR REPLACE FUNCTION POL_FUNCTION (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS 
    USER VARCHAR2(100);
BEGIN
    USER:=SYS_CONTEXT('USERENV', 'SESSION_USER');
    RETURN 'MANV = '''||USER||''''; 
END;
/
begin
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'NHOM11',
        OBJECT_NAME => 'UV_QLTRUCTIEP_NHANVIEN',
        POLICY_NAME => 'POLICY_QLTRUCTIEP',
        POLICY_FUNCTION => 'POL_FUNCTION',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS =>'LUONG, PHUCAP',
        SEC_RELEVANT_COLS_OPT => dbms_rls.ALL_ROWS
    );
end;
/
--CS3:
CREATE OR REPLACE VIEW UV_TRUONGPHONG_NHANVIEN AS
    SELECT *
    FROM NHANVIEN
    WHERE PHG = (SELECT NV2.PHG FROM NHANVIEN NV2 WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));
/
begin
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'NHOM11',
        OBJECT_NAME => 'UV_TRUONGPHONG_NHANVIEN',
        POLICY_NAME => 'POLICY_TRUONGPHONG',
        POLICY_FUNCTION => 'POL_FUNCTION',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS =>'LUONG, PHUCAP',
        SEC_RELEVANT_COLS_OPT => dbms_rls.ALL_ROWS
    );
end;
/
CREATE OR REPLACE VIEW UV_TRUONGPHONG_PHANCONG AS
    SELECT PC.*
    FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT PHG FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));
/
--CS4:Khong can tao view/vpd vi co the thuc hien tren bang
--CS5:
CREATE OR REPLACE VIEW UV_NHANSU_NHANVIEN AS SELECT * FROM NHANVIEN;
begin
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'NHOM11',
        OBJECT_NAME => 'UV_NHANSU_NHANVIEN',
        POLICY_NAME => 'POLICY_NHANSU',
        POLICY_FUNCTION => 'POL_FUNCTION',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS =>'LUONG, PHUCAP',
        SEC_RELEVANT_COLS_OPT => dbms_rls.ALL_ROWS,
        UPDATE_CHECK => TRUE
    );
end;
/
--CS6: 

--RL_NHANVIEN
GRANT SELECT ON PHONGBAN TO RL_NHANVIEN;
GRANT SELECT ON DEAN TO RL_NHANVIEN;
GRANT UPDATE (NGAYSINH,DIACHI,SODT) ON UV_NHANVIEN_NHANVIEN TO RL_NHANVIEN;
GRANT SELECT ON UV_NHANVIEN_NHANVIEN TO RL_NHANVIEN;
GRANT SELECT ON UV_NHANVIEN_PHANCONG TO RL_NHANVIEN;
/

--RL_QLTRUCTIEP
GRANT SELECT ON UV_QLTRUCTIEP_NHANVIEN TO RL_QLTRUCTIEP;
GRANT SELECT ON UV_QLTRUCTIEP_PHANCONG TO RL_QLTRUCTIEP;
/
--RL_NHANSU:
GRANT INSERT, UPDATE ON PHONGBAN TO RL_NHANSU;
GRANT SELECT ON UV_NHANSU_NHANVIEN TO RL_NHANSU;
GRANT UPDATE (MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG) ON UV_NHANSU_NHANVIEN TO RL_NHANSU;
/
--RL_TRUONGPHONG
GRANT SELECT ON UV_TRUONGPHONG_NHANVIEN TO RL_TRUONGPHONG;
GRANT SELECT, INSERT, DELETE, UPDATE ON UV_TRUONGPHONG_PHANCONG TO RL_TRUONGPHONG;
/
COMMIT;
--RL_TAICHINH
GRANT SELECT ON NHANVIEN TO RL_TAICHINH;
/
GRANT SELECT ON PHANCONG TO RL_TAICHINH;
/
GRANT UPDATE(PHUCAP, LUONG) ON NHANVIEN TO RL_TAICHINH;
/
--RL_TRUONGDA 
GRANT INSERT, UPDATE, DELETE ON DEAN TO RL_TRUONGDA;
/
GRANT RL_NHANVIEN TO RL_NHANSU;
/
GRANT RL_NHANVIEN TO RL_TRUONGDA;
/
GRANT RL_NHANVIEN TO RL_TRUONGPHONG;
/
GRANT RL_NHANVIEN TO RL_QLTRUCTIEP;
/
GRANT RL_NHANVIEN TO RL_TAICHINH;
/
COMMIT;
/
